version: "2"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./server/nginx:/etc/nginx/conf.d
      - web_cache:/var/cache/nginx
    networks:
      network:
        ipv4_address: 172.129.0.2
    ports:
      - 8000:80
    restart: always
  node:
    depends_on:
      - wordpress
      - nginx
    image: node:8
    volumes:
      - .:/opt/example
      - web_cache:/var/cache/nginx
    networks:
      network:
        ipv4_address: 172.129.0.3
    environment:
      WORDPRESS_HOST: http://wordpress
      NGINX_HOST: http://nginx
      NGINX_CACHE: /var/cache/nginx/data
    command: [node, /opt/example/server/index.js]
    restart: always
  db:
    image: mariadb:10
    volumes:
      - db_data:/var/lib/mysql
    networks:
      network:
        ipv4_address: 172.129.0.4
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wp_root:/var/www/html
      - ./server/wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      network:
        ipv4_address: 172.129.0.5
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    restart: always
volumes:
  wp_root:
  db_data:
  web_cache:
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.129.0.0/16
          gateway: 172.129.0.1
